'use client';

import { useEffect, useState, type FormEvent } from 'react';
import { Activity, CalendarDays, Check, ChevronDown, Clock3, Cross, GraduationCap, HeartHandshake, MapPin, Menu, MoonStar, Phone, ShieldCheck, Siren, Stethoscope, Syringe, Users, X } from 'lucide-react';

const phone = '+919177901230';
const maps = 'https://www.google.com/maps/search/?api=1&query=V+Care+Clinic+Aghapura+Nampally+Hyderabad';
const services = [
  { name: 'General Practitioner', icon: Stethoscope, text: 'Comprehensive primary healthcare for all age groups.', detail: 'Consultation for everyday health concerns, routine check-ups, and guidance on the next steps in your care.' },
  { name: 'Diabetologist', icon: Syringe, text: 'Diabetes care, management and prevention for a healthier life.', detail: 'Discuss blood sugar monitoring, your current treatment, lifestyle, and ongoing diabetes care with the doctor.' },
  { name: 'Infectious Disease Physician', icon: ShieldCheck, text: 'Diagnosis and treatment of bacterial, viral and other infections.', detail: 'Evaluation of fever and infection-related concerns, with investigations and treatment advised after a consultation.' },
  { name: 'Pulmonologist', icon: Activity, text: 'Care for respiratory conditions and lung problems.', detail: 'Consultation for cough, breathlessness, asthma, and other respiratory symptoms. Bring previous reports and prescriptions.' },
  { name: 'Sleep Clinic', icon: MoonStar, text: 'Consultation for sleep disorders and sleep-related issues.', detail: 'Talk to the doctor about snoring, disrupted sleep, and daytime sleepiness to understand appropriate evaluation and care.' },
];
function Brand({type = 'vcare'}: {type?: string}) { return <div className={`brand ${type}`}><span className="brand-symbol"><Cross size={35}/></span><div>{type === 'highcare' && <small>PRIME</small>}<strong>{type === 'highcare' ? 'HIGH CARE' : type === 'procare' ? 'PRO CARE' : 'V CARE'}</strong><span>{type === 'vcare' ? '— CLINIC —' : 'H O S P I T A L S'}</span></div></div>; }
function ClinicBanner() { return <div className="clinic-banner"><div className="clinic-card"><Brand type="highcare"/><div className="timing"><Clock3 size={12}/> Mon to Sat: 10:00 AM to 2:00 PM</div><p><MapPin/> Attapur, Pillar Number-102,<br/>Langar Houz, HYD</p><a href="tel:+919160062106"><Phone/>91 600 21 606</a></div><div className="clinic-card pro"><span className="motto">“We Treat, He Cures”</span><Brand type="procare"/><div className="timing"><Clock3 size={12}/> Mon to Sat: 6:00 PM to 8:00 PM</div><p><MapPin/> Beside Matrajan Hotel,<br/>Musheerabad, Hyderabad</p><a href="tel:+919848188898"><Phone/>98481 88898</a></div><div className="clinic-card"><Brand/><div className="timing"><Clock3 size={12}/> Mon to Sat: 4:00 PM to 6:00 PM</div><p><MapPin/> Near Alhamdulillah Hotel,<br/>Aghapura, Nampally</p><a href={`tel:${phone}`}><Phone/>91779 01230</a></div><div className="emergency"><Siren size={49} strokeWidth={1.6}/><div><strong>24/7</strong><span>Emergency<br/>Critical Care<br/>Pharmacy<br/>Diagnostics</span></div><small>Hospital emergency services</small></div></div>; }

export default function Home() {
 const [menu, setMenu] = useState(false);
 const [selected, setSelected] = useState<number | null>(null);
 const [request, setRequest] = useState('');
 const [error, setError] = useState('');
 const [today, setToday] = useState('');
 useEffect(() => {
   const date = new Date();
   setToday(`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`);
 }, []);
 useEffect(() => {
   if (!menu) return;
   const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setMenu(false); };
   window.addEventListener('keydown', close);
   return () => window.removeEventListener('keydown', close);
 }, [menu]);
 function submit(e: FormEvent<HTMLFormElement>) {
   e.preventDefault();
   const data = new FormData(e.currentTarget);
   const name = String(data.get('name') || '').trim();
   const mobile = String(data.get('phone') || '').replace(/[\s()+-]/g, '');
   const date = String(data.get('date') || '');
   const now = new Date();
   const localToday = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
   setRequest('');
   if (!name) { setError('Please enter your full name.'); return; }
   if (!/^(?:91)?[6-9][0-9]{9}$/.test(mobile)) { setError('Please enter a valid 10-digit Indian mobile number, optionally with +91.'); return; }
   if (!date || date < localToday) { setError('Please choose today or a future date.'); return; }
   if (new Date(`${date}T12:00:00`).getDay() === 0) { setError('The clinic is closed on Sunday. Please choose Monday to Saturday.'); return; }
   setError('');
   setRequest(`Hello V Care Clinic, I would like to request an appointment. Name: ${name}. Phone: ${mobile}. Preferred date: ${date}. Service: ${data.get('service')}. Please call me to confirm availability.`);
 }

 return <div className="site-shell" id="home"><a className="skip" href="#main">Skip to content</a>
  <div className="topbar"><span><MapPin/>V Care Clinic, Behind Habeeb Nagar PS, Aghapura, Nampally, Hyderabad</span><a href={`tel:${phone}`}><Phone/>+91 91779 01230</a><span><Clock3/>Mon – Sat: 4:00 PM – 6:00 PM</span></div>
  <header><a href="#home" aria-label="V Care Clinic home"><Brand/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Toggle navigation" aria-controls="main-navigation">{menu ? <X/> : <Menu/>}</button><nav id="main-navigation" className={menu ? 'open' : ''}>{[['Home','home'],['About Doctor','about'],['Services','services'],['Conditions We Treat','conditions'],['Reviews','reviews'],['FAQ','faq'],['Contact','contact']].map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</nav><a className="button nav-book" href="#appointment"><CalendarDays/>Book Appointment</a></header>
  <main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow">V CARE CLINIC · HYDERABAD</p><h1>Dr. Mohd<br/><strong>Vaseem<span>.</span></strong></h1><h2>Personal care.<br/>A healthier you.</h2><p className="specialty-line">General Practitioner <b>·</b> Diabetologist <b>·</b> Infectious Disease Physician <b>·</b> Pulmonologist <b>·</b> Sleep Clinic</p><p>Thoughtful consultations. Clear answers. Care that starts with listening to you.</p><div className="hero-actions"><a className="button" href={`tel:${phone}`}><Phone/><span>Call Now<small>+91 91779 01230</small></span></a><a className="button outline" href="#appointment"><CalendarDays/>Book Appointment</a><a className="button outline" href={maps} target="_blank" rel="noreferrer"><MapPin/>Get Directions</a></div></div><div className="hero-photo"><img src="/images/dr-vaseem.jpg" alt="Dr. Mohd Vaseem"/><div className="photo-caption"><GraduationCap/><div><span>MBBS · MD · FCCP (USA)</span><strong>Dr. Mohd Vaseem</strong></div></div></div><aside className="hero-info"><div><Stethoscope/><p><strong>Multi-specialty care</strong><span>Care for you and your family</span></p></div><div><MapPin/><p><strong>Aghapura, Nampally</strong><span>Hyderabad, Telangana</span></p></div><div><Clock3/><p><strong>Mon – Sat</strong><span>4:00 PM – 6:00 PM<br/>Sunday closed</span></p></div></aside></section>
  <section className="trust-strip" aria-label="Our approach">{[[Stethoscope,'Experienced Doctor','Thoughtful, personal medical care.'],[HeartHandshake,'Patient First Approach','We listen, we care, we heal.'],[ShieldCheck,'Affordable Care','Ask us about consultation fees.'],[Users,'Care for Your Family','Support through every stage.']].map(([Icon,title,description])=>{const I=Icon as typeof Stethoscope;return <div key={String(title)}><I/><p><strong>{String(title)}</strong><span>{String(description)}</span></p></div>;})}</section>
  <section className="section" id="services"><div className="section-title"><div><p className="eyebrow">01 / EXPERTISE</p><h2>Specialized care.<br/><span>One personal approach.</span></h2></div><p>From everyday health to ongoing care,<br/>find the support you need.</p></div><div className="service-grid">{services.map((s,i)=><article className="service-card" key={s.name}><span className="service-number">0{i+1}</span><div className="service-icon"><s.icon/></div><h3>{s.name}</h3><p>{s.text}</p><button className="small-button" onClick={()=>setSelected(selected===i ? null : i)} aria-expanded={selected===i}>Learn More <ChevronDown size={13}/></button></article>)}</div>{selected !== null && <div className="service-detail"><div><h3>{services[selected].name}</h3><p>{services[selected].detail}</p><a href="#appointment" className="text-link">Request a consultation →</a></div><button onClick={()=>setSelected(null)} aria-label="Close service details"><X/></button></div>}</section>
  <section className="about section" id="about"><img src="/images/dr-vaseem.jpg" loading="lazy" alt="Dr. Mohd Vaseem at the clinic"/><div className="about-copy"><p className="eyebrow">02 / MEET YOUR DOCTOR</p><h2>A conversation.<br/>A connection.<br/><em>Better care.</em></h2><h3 className="doctor-name">Dr. Mohd Vaseem</h3><p>Dr. Mohd Vaseem offers consultations at V Care Clinic in Aghapura, Nampally, Hyderabad.</p><p>From everyday health concerns to ongoing care, your consultation is a chance to discuss your symptoms, understand your options, and plan your next steps.</p><div className="credentials"><GraduationCap/><span>MBBS, MD, FCCP (USA)<small>CCEBDM, FCD</small></span></div><a href="#appointment" className="button">Book a Consultation</a></div><div className="about-facts"><div><Users/><strong>Personal</strong><span>Attention & care</span></div><div><HeartHandshake/><strong>Family</strong><span>Focused approach</span></div><div><CalendarDays/><strong>5</strong><span>Specializations</span></div><div><MapPin/><strong>Hyderabad</strong><span>Convenient location</span></div></div></section>
  <section className="conditions section" id="conditions"><div><h2>Care for everyday concerns</h2><p>Speak to the doctor about your symptoms and ongoing health needs.</p></div><div className="condition-tags">{['General health','Diabetes care','Fever & infections','Breathing concerns','Sleep concerns'].map(t=><span key={t}><Check size={14}/>{t}</span>)}</div></section>
  <div className="appointment-heading section"><p className="eyebrow">03 / PLAN YOUR VISIT</p><h2>Let’s make time<br/><span>for your health.</span></h2></div><section className="visit-grid section"><div id="reviews" className="review-panel"><h2>What Patients Say</h2><HeartHandshake className="review-symbol"/><p className="review-intro">Your experience matters.</p><p>Read patient experiences on Google, or share your feedback after visiting the clinic.</p><div className="review-note"><HeartHandshake/><p>A little time. A listening ear.<br/><strong>Care centered around you.</strong></p></div><a className="button" href={maps} target="_blank" rel="noreferrer"><span className="google">G</span>View Clinic on Google</a></div>
  <div id="appointment" className="booking"><h2>Book an Appointment</h2><p className="muted">Tell us when you’d like to visit.</p><form onSubmit={submit} onChange={() => { setRequest(''); setError(''); }}><div className="form-grid"><label>Full name<input name="name" autoComplete="name" placeholder="Your full name" required maxLength={100}/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" placeholder="10-digit mobile" inputMode="tel" maxLength={18} required/></label><label>Preferred date<input name="date" type="date" min={today || undefined} required/></label><label>Consultation<select name="service">{services.map(s=><option key={s.name}>{s.name}</option>)}</select></label></div><p className="form-note">Clinic hours: Mon–Sat, 4–6 PM. Reception will confirm availability. Your details are only included in the message you choose to send.</p>{error && <p className="form-error" role="alert">{error}</p>}<button className="button" type="submit"><CalendarDays/>Prepare Appointment Request</button></form>{request && <div className="request-result" role="status"><strong>Your request is ready.</strong><p>Review your details, then send them to reception on WhatsApp. Your appointment is confirmed only after reception replies.</p><p className="request-preview">{request}</p><a className="button" href={`https://wa.me/919177901230?text=${encodeURIComponent(request)}`} target="_blank" rel="noreferrer">Continue to WhatsApp</a></div>}</div>
  <div id="contact" className="location"><h2>Clinic Location</h2><div className="location-copy"><MapPin/><p><strong>V Care Clinic</strong><br/>Behind Habeeb Nagar PS,<br/>Near Alhamdulillah Hotel,<br/>Aghapura, Nampally,<br/>Hyderabad, Telangana.</p></div><a className="contact-line" href={`tel:${phone}`}><Phone/>+91 91779 01230</a><p className="contact-line"><Clock3/>Mon – Sat: 4:00 PM – 6:00 PM<br/>Sunday closed</p><a className="map-card" href={maps} target="_blank" rel="noreferrer"><MapPin/><strong>Find us in Aghapura</strong><span>Open in Google Maps ↗</span></a><div className="location-buttons"><a className="button outline" href={maps} target="_blank" rel="noreferrer"><MapPin/>Directions</a><a className="button" href={`tel:${phone}`}><Phone/>Call Now</a></div></div></section>
  <section className="faq section" id="faq"><div><p className="eyebrow">04 / GOOD TO KNOW</p><h2>A little clarity.<br/>Before your visit.</h2></div>{[['How do I book an appointment?','Prepare an appointment request using the form above and send it to reception on WhatsApp, or call the clinic. Reception will confirm your visit.'],['What are the clinic timings?','V Care Clinic consultations are listed Monday to Saturday, 4:00 PM to 6:00 PM. Please call ahead to confirm the doctor’s availability.'],['What should I bring to my consultation?','Bring your previous prescriptions, test reports, and a list of any medicines you currently take.']].map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={16}/></summary><p>{a}</p></details>)}</section>
  <section className="practice-locations" id="clinics"><div className="section-title section"><div><p className="eyebrow">05 / OUR LOCATIONS</p><h2>Care, closer to you.</h2></div><p>Find the right location for your visit.<br/>Call ahead to confirm availability.</p></div><ClinicBanner/></section></main><footer><div className="footer-grid"><div><Brand/><p>Providing thoughtful healthcare with compassion and personal attention.</p><a href={`tel:${phone}`}><Phone size={15}/> +91 91779 01230</a></div><div><h3>Quick Links</h3>{[['Home','home'],['About Doctor','about'],['Services','services'],['Reviews','reviews'],['FAQ','faq'],['Contact','contact']].map(([t,id])=><a key={id} href={`#${id}`}>{t}</a>)}</div><div><h3>Our Specializations</h3>{services.map((s,i)=><a key={s.name} href="#services" onClick={()=>setSelected(i)}>{s.name}</a>)}</div><div><h3>Contact Info</h3><p>V Care Clinic, Behind Habeeb Nagar PS,<br/>Near Alhamdulillah Hotel,<br/>Aghapura, Nampally, Hyderabad.</p><p>Mon – Sat: 4:00 PM – 6:00 PM<br/>Sunday closed</p></div></div><div className="copyright">© {new Date().getFullYear()} V Care Clinic · Dr. Mohd Vaseem. All rights reserved.<span>Appointments subject to confirmation.</span></div></footer>
 </div>;
}
